# Generated by Django 5.2.5 on 2025-08-09 07:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_name_si', models.CharField(blank=True, help_text='Business name in Sinhala', max_length=200)),
                ('business_name_ta', models.CharField(blank=True, help_text='Business name in Tamil', max_length=200)),
                ('category', models.CharField(choices=[('millet_food', 'Millet Food Shops'), ('gym', 'Gyms & Fitness Centers'), ('zumba', 'Zumba & Dance Studios'), ('nutritionist', 'Nutritionists & Dietitians'), ('yoga', 'Yoga Studios'), ('personal_trainer', 'Personal Trainers'), ('ayurveda', 'Ayurvedic Centers'), ('mental_health', 'Mental Health Counselors'), ('spa', 'Spas & Wellness Centers'), ('physiotherapy', 'Physiotherapy Centers'), ('meditation', 'Meditation Centers'), ('martial_arts', 'Martial Arts Schools')], max_length=20)),
                ('subcategory', models.CharField(blank=True, help_text='Specific type within category', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('colombo', 'Colombo'), ('gampaha', 'Gampaha'), ('kalutara', 'Kalutara'), ('kandy', 'Kandy'), ('matale', 'Matale'), ('nuwara_eliya', 'Nuwara Eliya'), ('galle', 'Galle'), ('matara', 'Matara'), ('hambantota', 'Hambantota'), ('jaffna', 'Jaffna'), ('kurunegala', 'Kurunegala'), ('anuradhapura', 'Anuradhapura'), ('badulla', 'Badulla'), ('ratnapura', 'Ratnapura'), ('ampara', 'Ampara'), ('batticaloa', 'Batticaloa'), ('trincomalee', 'Trincomalee')], max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField()),
                ('description_si', models.TextField(blank=True, help_text='Description in Sinhala')),
                ('description_ta', models.TextField(blank=True, help_text='Description in Tamil')),
                ('operating_hours', models.JSONField(default=dict, help_text='Weekly operating hours')),
                ('amenities', models.JSONField(default=list, help_text='Available amenities')),
                ('pricing_info', models.TextField(blank=True, help_text='General pricing information')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_documents', models.FileField(blank=True, upload_to='provider_verifications/')),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('accepts_online_bookings', models.BooleanField(default=True)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='provider_images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='providers.provider')),
            ],
            options={
                'ordering': ['sort_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_si', models.CharField(blank=True, max_length=200)),
                ('name_ta', models.CharField(blank=True, max_length=200)),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('session', 'Training Session'), ('class', 'Group Class'), ('workshop', 'Workshop'), ('treatment', 'Treatment'), ('package', 'Package Deal')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('max_participants', models.PositiveIntegerField(default=1)),
                ('is_bookable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.provider')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['category', 'district'], name='providers_p_categor_41ccc8_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['status', 'is_verified'], name='providers_p_status_849d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['latitude', 'longitude'], name='providers_p_latitud_07070d_idx'),
        ),
    ]
