# Generated by Django 5.2.5 on 2025-08-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='category',
            field=models.CharField(choices=[('millet_food', 'Millet Food Shops'), ('gym', 'Gyms & Fitness Centers'), ('zumba', 'Zumba & Dance Studios'), ('nutritionist', 'Nutritionists & Dietitians'), ('dietitian', 'Clinical Dietitians'), ('meal_delivery', 'Meal Delivery Services'), ('healthy_food', 'Healthy Food Stores'), ('yoga', 'Yoga Studios'), ('personal_trainer', 'Personal Trainers'), ('ayurveda', 'Ayurvedic Centers'), ('mental_health', 'Mental Health Counselors'), ('spa', 'Spas & Wellness Centers'), ('physiotherapy', 'Physiotherapy Centers'), ('meditation', 'Meditation Centers'), ('martial_arts', 'Martial Arts Schools')], max_length=20),
        ),
    ]
