# Generated by Django 5.2.5 on 2025-08-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('walk', 'Walk'), ('run', 'Run'), ('cycle', 'Cycle'), ('workout', 'Workout'), ('yoga', 'Yoga'), ('other', 'Other')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('distance_km', models.FloatField(default=0)),
                ('calories_burned', models.FloatField(default=0)),
                ('started_at', models.DateTimeField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
